### ISSUE TITLE
Integration with nf-core/nanoseq

### ISSUE THREAD

**Issue by drpatelh** [connor-lab/ncov2019-artic-nf#1]
Hi @m-bull ! Hope you are well. I was wondering whether you think it would be worthwhile adding this workflow as an extension to the [nf-core/nanoseq](https://github.com/nf-core/nanoseq) pipeline? I have spoken to @will-rowe from @nickloman group about this on nf-core Slack and there was some interest in adding it as a stand-alone pipeline. The advantage of adding it directly to the `nanoseq` pipeline is that some of the standard tools/steps used for Nanopore data processing have been integrated into the pipeline and have been extensively tested already on various compute platforms. Having said that, we are also in the process of adding an [nf-core/covid19](https://github.com/nf-core/covid19) pipeline which is based on [this Galaxy implementation](https://github.com/galaxyproject/SARS-CoV-2).

I dont know enough about the specific tools/steps required for this kind of pipeline but I am more than happy to help with the implementation with the hope that we can lean on each other's expertise to get a working pipeline together.

Would be great to hear your thoughts :) We also have dedicated channels on the nf-core Slack workspace for #nanoseq and #covid19:
https://nf-co.re/join

**Comment by m-bull** [comment]
Hi @drpatelh - apologies for being slow to respond to this. This workflow is pretty tightly coupled to ARTIC, and written in DSL2, so I'm not sure how easy the implementation would be. I'm also afraid that I don't have much time to contribute to your project myself, but please feel free to fork this and go for it!

**Comment by drpatelh** [comment]
Hi @m-bull . No worries :) Having had a more in-depth look at your implementation it is indeed evident that quite a few of the steps are essentially wrapping the scripts in the ARTIC GitHub repo. Without knowing what the future plans are with regard to the maintenance of this repo it's probably not a worthwhile effort trying to have another implementation in Nextflow because the pipeline you have written does that quite well already. Also, I am not too keen to start developing this pipeline without some clear direction that can only really be gained via collaborators from ARCTIC. 

We are currently implementing the infrastructure, rules, linting etc to provide DSL 2 modules to the Nextflow community so hopefully most pipelines including `nanoseq` will be ported to this in the near future:
https://github.com/nf-core/modules

Please do think of us in the future when embarking on a project such as this because it would have been great to have this pipeline on nf-core. Hopefully, you are already aware of the advantages. 

May want to remove/update this 😅:
https://github.com/connor-lab/ncov2019-artic-nf/blob/28cab17119de1d7d6622e6b2226d6ff33ab711d8/nextflow.config#L3

What is the current state of the pipeline and future plans? e.g.
* Does it run from end-to-end?
* Have you compared it to the results coming out of the native ARCTIC pipeline?
* Are you planning to release it anytime soon?
* Will it have tagged Docker/Singularity containers to fulfill reproducibility? 

I realise that time is always the main sticking point but I am only asking because I would be more than happy to point people in your direction if the opportunity arises 👍 

PS: We had a couple of participants from PHW at the recent nf-core Hackathon who actually contributed quite alot to our DSL 2 efforts 😎. If I remember correctly, Thomas Connor signed up too.

**Comment by m-bull** [comment]
The source of my inspiration revealed! :)

1. It runs from end to end
2. It essentially automates the pipeline, so should be identical
3. Once its been battle-tested on a few systems, which is happening as we speak
4. Absolutely

Full release/reproducibility is a little while off for now - we're very focussed on sequencing and building consensus sequences from COV2 samples ATM. We'll be generating _loads_ of publicly available data in the near future...

**Comment by drpatelh** [comment]
Hi @m-bull ! Hope you are well. Wowzas, alot has happened since I initially created this issue 😏 Thank you and everyone else involved here for your efforts with this pipeline and the COVID-19 fight in general. I have been using this pipeline for all of our in house Nanopore sequencing contributions to COG-UK.

As you would have probably seen, we wrote an Illumina pipeline ([nf-core/viralrecon](https://github.com/nf-core/viralrecon)) that was able to do both amplicon and metagenomics type analysis. This has had a couple of releases now and after being distracted for a while with re-writing the nf-core/rnaseq pipeline in DSL2 and setting up [nf-core/modules](https://github.com/nf-core/modules), I have now almost finished porting viralrecon to DSL2 as it was the next logical step in the development of the pipeline. We are now able to use one container per process and a bunch of other cool stuff like user-level modification of tool parameters via custom configs. 

Given that the remit of the pipeline was quite generic to begin with, I have now added Nanopore support for the ARTIC field bioinformatics pipeline and although the primary implementation is quite different, I used your pipeline as a source of inspiration and I would like to ensure that you and anyone else you suggest are acknowledged appropriately 🙂

We still have to tie up a few things like missing software on Bioconda, docs, loads of testing etc but hopefully the pipeline should be ready for a release soon. If you are interested in having a look the current code is sitting on the [`dev`](https://github.com/nf-core/viralrecon/tree/dev) branch. 

I have already written a paragraph in the [Credits](https://github.com/nf-core/viralrecon/tree/dev#credits) section acknowledging this pipeline but please do let me know if I should change anything.

Thanks again!
