### ISSUE TITLE
schemeRepoURL can no longer be used with local path

### ISSUE THREAD

**Issue by sb10** [connor-lab/ncov2019-artic-nf#20]
https://github.com/connor-lab/ncov2019-artic-nf/pull/16 had changes to detect if schemeRepoURL was a local path and avoid the git clone of the scheme repo if so.

Subsequent commit removed this capability.

It's not in use by us anymore (we will use `--bed` and `--ref`), but just wanted to know if the change was intentional.

If it was, the README.md should be edited to remove the explanation of using schemeRepoURL with a local path.

**Comment by m-bull** [comment]
Hi @sb10 - as `git` supports cloning from local filesystems, you can still use `--schemeRepoURL` to move a local repo into the workflow, avoiding internet connectivity, it must just be in the format of `file:///path/to/repo`.

You are right though, the README.md should be update to reflect this.
