### ISSUE TITLE
reconcile nextflow profiles

### ISSUE THREAD

**Issue by thanhleviet** [connor-lab/ncov2019-artic-nf#21]
The current slurm profile is (likely) defined for PWH system, would be great if we could have basic and institutional profiles, e.g.

slurm - only define slurm as excutor
pwh - slurm executor + specific partitions
sanger - lsf + specific computing resources...

Thanks

**Comment by sb10** [comment]
Agreed.

If this repo is willing to accept a `conf/sanger.config` and `-sanger` profile, it would obviate the need for us to maintain our own fork.

While we could just have a config file outside the repo, it feels nicer to have it under version control so mistakes can't happen with not using it.

**Comment by m-bull** [comment]
Happy to accept PRs on this @thanhleviet and @sb10.

I suggest a model for this in https://github.com/connor-lab/ncov2019-artic-nf/commit/0400879f262cdaa8eb35e1f369ac04b2d92a3e8b - essentially, add a profile to `conf/coguk.config` and a file to `conf/coguk` with your settings.

Hope this is useful!

**Comment by thanhleviet** [comment]
Great! Many thanks both.
