### ISSUE TITLE
mandatory parameters in medaka subworkflow

### ISSUE THREAD

**Issue by nbargues** [connor-lab/ncov2019-artic-nf#29]
Hi, 

In your medaka subworkflow, the parameter  --fast5_pass and --sequencing_summary are mandatory for running the analysis. 

But it's not really the case, medaka don't need those argument, just nanopolish.

example with the artic pipeline : 
`artic minion --medaka --normalise 200 --threads 4 --scheme-directory ~/artic-ncov2019/primer-schemes --read-file run_name_barcode01.fastq nCoV-2019/V1 samplename`

Can you remove the fact that those parameters are mandatory or just indicate what to change in your code to do that ? 

Regards

**Comment by m-bull** [comment]
Thanks @nbargues - I've pushed a fix for this (https://github.com/connor-lab/ncov2019-artic-nf/commit/505304dfe7d00706d33174b8e362d00c1a6b395e).

**Comment by nbargues** [comment]
Thanks, it works well !
