### ISSUE TITLE
Error running articGuppyplex

### ISSUE THREAD

**Issue by sthifx** [connor-lab/ncov2019-artic-nf#31]
When running the latest version on our nanopore data, I'm getting the following error:

File "PATH/lib/python3.6/site-packages/artic/pipeline.py", line 35, in run_subtool
      submodule.run(parser, args)
    File "PATH/python3.6/site-packages/artic/guppyplex.py", line 36, in run
      fastq_outfn = "%s_%s.fastq" % (args.prefix, os.path.basename(barcode_directory))
NameError: name 'barcode_directory' is not defined

It looks like barcode_directory is never instantiated in guppyplex.py

The offending command from the nextflow work directory in .command.sh is 

`artic guppyplex     --min-length 400     --max-length 700     --prefix PREFIX     --directory barcode04`

Apologies if this is me being daft, and thanks in advance!

**Comment by m-bull** [comment]
Sorry about that, not you being daft at all! A product of everything moving very quickly at the moment, and it looks like ARTIC broke something on the master branch of the fieldbioinformatics [repo](https://github.com/artic-network/fieldbioinformatics). This workflow probably shouldn't use the master branch from there anyway! 

I've pinned the commit id of fieldbioinformatics in https://github.com/connor-lab/ncov2019-artic-nf/commit/dd5cb0603b56ba61feb11222e4acd9fe9630c846 - this works fine in my hands. Please update your containers if you've made any. Conda should work fine just using https://github.com/connor-lab/ncov2019-artic-nf/commit/dd5cb0603b56ba61feb11222e4acd9fe9630c846.

**Comment by sthifx** [comment]
Thanks Matt, and thanks for the v fast response! Seems to be working great now.

All the best, Sam
