### ISSUE TITLE
ivar 1.2.3 conda dependency conflict

### ISSUE THREAD

**Issue by jts** [connor-lab/ncov2019-artic-nf#65]
Just a head's up when you update ivar, when we changed our local version to ivar 1.2.3 conda fails to solve the environment. @mlaszloffy fixed this by changing the samtools and pysam versions:

```
--- a/environments/illumina/environment.yml
+++ b/environments/illumina/environment.yml
@@ -8,7 +8,7 @@ dependencies:
   - biopython=1.74
   - pandas=0.23.0=py36_1
   - bwa=0.7.17=pl5.22.0_2
-  - samtools=1.9
+  - samtools=1.10
   - trim-galore=0.6.5
   - ivar=1.2.3
-  - pysam=0.15.2
+  - pysam=0.16.0.1
```

**Comment by m-bull** [comment]
Cheers @jts and @mlaszloffy - `ivar` at 1.2.3 in https://github.com/connor-lab/ncov2019-artic-nf/commit/bc9884de54445eeeb5a73cb2f50fc2f10c9f3b4a.
