### ISSUE TITLE
Error: Nextflow

### ISSUE THREAD

**Issue by yockping** [connor-lab/ncov2019-artic-nf#67]
Hi, 

Earlier, I managed to execute the code:
./nextflow run connor-lab/ncov2019-artic-nf -profile conda --illumina --prefix run1_result --directory run1

However, when I try to rerun the same code, I encountered the following error:
_Error executing process > 'ncovIllumina:prepareReferenceFiles:articDownloadScheme (https://github.com/artic-network/artic-ncov2019.git)'

Caused by:
  Missing output file(s) `scheme/**/V2/*.reference.fasta` expected by process `ncovIllumina:prepareReferenceFiles:articDownloadScheme (https://github.com/artic-network/artic-ncov2019.git)`

Command executed:

  git clone https://github.com/artic-network/artic-ncov2019.git scheme

Command exit status:
  0

Command output:
  (empty)

Command error:
  Cloning into 'scheme'...

Work dir:
  /home/yp/work/a5/5dddf7b46f7974ef772b1545611245

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

Please need your advice to fix this problem._ 

Many thanks

**Comment by m-bull** [comment]
Should be fixed by https://github.com/connor-lab/ncov2019-artic-nf/commit/bc9884de54445eeeb5a73cb2f50fc2f10c9f3b4a.
