### ISSUE TITLE
Command failed: nanopolish index

### ISSUE THREAD

**Issue by sthifx** [connor-lab/ncov2019-artic-nf#73]
Hello,

I've recently encountered an issue a couple of times where nanopolish fails.  Tracing through the work directory and logs, this seems to occur when

1. There are sufficient reads associated with a barcode (e.g. in one case, 318 fastq reads for barcode24), so that the barcode _does_ get processed
2. Guppyplex throws all of these reads away as they're too long/short, creating an empty fastq file.
3. artic minion then fails trying to index this empty fastq file

This error doesn't occur if there are no/very few input reads from a sample prior to guppyplex as I understand that the sample wouldn't be put through guppyplex at all in this case. 

If this is a real issue, would it be possible to put in a check either after guppyplex, or at the start of artic minion, for empty fastq files?

Apologies if this is down to me rather than an actual issue, and please let me know if you need any more info.

Thanks and all the best,

Sam

**Comment by m-bull** [comment]
Hi Sam - just pushed a fix for this. There's a new option: `minReadsArticGuppyPlex`, which will filter samples with fewer than its value after the `artic guppyplex` process. Its set to 10 by [default](https://github.com/connor-lab/ncov2019-artic-nf/blob/1eed11b29ff1bf2375a822454f451fdf7d4aa800/conf/nanopore.config#L25).

**Comment by sthifx** [comment]
Great, thanks for this - I've tested on a sample that previously failed and it works perfectly.

Thanks again!
