### ISSUE TITLE
Using the pipeline for non-artic primers?!

### ISSUE THREAD

**Issue by ahmedmagds** [connor-lab/ncov2019-artic-nf#93]
I just want to make sure I can use this pipeline with illumina reads produced by primers (paragon kit) other than the artic primers. This is the command I am planning to use.
`nextflow run ncov2019-artic-nf/ -profile conda --illumina --scheme paragon --outdir ncov_results --bed paragon_primer.bed --ref Reference.fasta --prefix ncov_paragon --directory sars-cov-2_reads/`

**Comment by ahmedmagds** [comment]
@m-bull Could you please help me with my question?

**Comment by m-bull** [comment]
Hi @ahmedmagds, I've never used the kit that you describe and I've not seen the bedfile associated with it, so I can't comment on how likely this is to work.

I suggest that you extensively test a positive control sample to establish whether the pipeline behaviour is what you expect.
